const employees = [
  {
    id: "EMP001",
    name: "Shorya Sharma",
    email: "shorya.sharma@company.com",
    password: "shorya123", // In practice, use bcrypt or similar
    department: "Design",
    role: "UI/UX Designer",
    taskCount: {
      active: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        completed: false,
        failed: false,
        priority: "High",
        taskTitle: "Design Landing Page",
        taskDescription:
          "Create a responsive landing page for the new product launch.",
        taskDate: "2025-07-03",
        category: "Design",
      },
      {
        active: false,
        completed: true,
        failed: false,
        priority: "Medium",
        taskTitle: "Update Style Guide",
        taskDescription:
          "Revise the company style guide with new color schemes.",
        taskDate: "2025-06-25",
        category: "Design",
      },
      {
        active: false,
        completed: false,
        failed: true,
        priority: "High",
        taskTitle: "Prototype Mobile App",
        taskDescription: "Develop an interactive prototype for the mobile app.",
        taskDate: "2025-06-15",
        category: "Design",
      },
      {
        active: true,
        completed: false,
        failed: false,
        priority: "Low",
        taskTitle: "Create Icon Set",
        taskDescription:
          "Design a set of custom icons for the web application.",
        taskDate: "2025-07-05",
        category: "Design",
      },
    ],
  },
  {
    id: "EMP002",
    name: "Roshan Patel",
    email: "roshan.patel@company.com",
    password: "roshan123",
    department: "Marketing",
    role: "Marketing Specialist",
    taskCount: {
      active: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        completed: false,
        failed: false,
        priority: "Medium",
        taskTitle: "Create Marketing Banner",
        taskDescription:
          "Design a promotional banner for the summer sale campaign.",
        taskDate: "2025-07-06",
        category: "Design",
      },
      {
        active: false,
        completed: true,
        failed: false,
        priority: "Low",
        taskTitle: "Review Blog Post",
        taskDescription: "Proofread and finalize blog content for publication.",
        taskDate: "2025-06-28",
        category: "Content",
      },
      {
        active: true,
        completed: false,
        failed: false,
        priority: "Medium",
        taskTitle: "Analyze User Analytics",
        taskDescription: "Gather insights from user behavior for Q2 2025.",
        taskDate: "2025-07-04",
        category: "Research",
      },
      {
        active: false,
        completed: false,
        failed: true,
        priority: "High",
        taskTitle: "Update Pricing Model",
        taskDescription: "Adjust tier structure in pricing calculator.",
        taskDate: "2025-06-22",
        category: "Business",
      },
    ],
  },
  {
    id: "EMP003",
    name: "Mayank Gupta",
    email: "mayank.gupta@company.com",
    password: "mayank123",
    department: "Engineering",
    role: "Backend Developer",
    taskCount: {
      active: 2,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        completed: false,
        failed: false,
        priority: "High",
        taskTitle: "Setup Database Schema",
        taskDescription: "Design and implement the schema for the new module.",
        taskDate: "2025-07-06",
        category: "Development",
      },
      {
        active: false,
        completed: true,
        failed: false,
        priority: "Medium",
        taskTitle: "Conduct Sprint Review",
        taskDescription: "Lead the team sprint review meeting.",
        taskDate: "2025-06-25",
        category: "Management",
      },
      {
        active: false,
        completed: false,
        failed: true,
        priority: "High",
        taskTitle: "Test Payment Gateway",
        taskDescription: "Ensure all transactions are secure and logged.",
        taskDate: "2025-06-18",
        category: "Testing",
      },
      {
        active: true,
        completed: false,
        failed: false,
        priority: "High",
        taskTitle: "Refactor API Code",
        taskDescription: "Improve performance and readability of APIs.",
        taskDate: "2025-07-03",
        category: "Development",
      },
      {
        active: false,
        completed: true,
        failed: false,
        priority: "Low",
        taskTitle: "Update Documents",
        taskDescription: "Revise integration docs based on latest API changes.",
        taskDate: "2025-06-27",
        category: "Documentation",
      },
    ],
  },
  {
    id: "EMP004",
    name: "Abhishek Kumar",
    email: "abhishek.kumar@company.com",
    password: "abhishek123",
    department: "Frontend",
    role: "Frontend Developer",
    taskCount: {
      active: 2,
      completed: 0,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        completed: false,
        failed: false,
        priority: "Medium",
        taskTitle: "Optimize Images",
        taskDescription: "Compress and resize images for faster load times.",
        taskDate: "2025-07-05",
        category: "Performance",
      },
      {
        active: false,
        completed: false,
        failed: true,
        priority: "Low",
        taskTitle: "Prepare SEO Report",
        taskDescription: "Analyze ranking and backlink status for Q2 2025.",
        taskDate: "2025-06-20",
        category: "Marketing",
      },
      {
        active: true,
        completed: false,
        failed: false,
        priority: "High",
        taskTitle: "Build Login Page",
        taskDescription: "Create responsive login with Clerk authentication.",
        taskDate: "2025-07-04",
        category: "Frontend",
      },
    ],
  },
  {
    id: "EMP005",
    name: "Sachin Verma",
    email: "sachin.verma@company.com",
    password: "sachin123",
    department: "Quality Assurance",
    role: "QA Engineer",
    taskCount: {
      active: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: false,
        completed: true,
        failed: false,
        priority: "Low",
        taskTitle: "Create Test Cases",
        taskDescription: "Write and run test cases for user registration flow.",
        taskDate: "2025-06-29",
        category: "Testing",
      },
      {
        active: true,
        completed: false,
        failed: false,
        priority: "Medium",
        taskTitle: "Test Mobile Responsiveness",
        taskDescription: "Verify UI responsiveness across devices.",
        taskDate: "2025-07-06",
        category: "Testing",
      },
      {
        active: true,
        completed: false,
        failed: false,
        priority: "Low",
        taskTitle: "Write Help Docs",
        taskDescription: "Prepare onboarding help docs for new users.",
        taskDate: "2025-07-05",
        category: "Documentation",
      },
      {
        active: false,
        completed: false,
        failed: true,
        priority: "High",
        taskTitle: "Fix Production Bug",
        taskDescription:
          "Investigate and resolve issue in transaction summary.",
        taskDate: "2025-06-24",
        category: "Bugfix",
      },
    ],
  },
];

export default employees;
